
name: Test static build on IPFS

on:
  workflow_dispatch:
  pull_request:
    branches:
      - v2
  
jobs:
  static-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true 
        token: ${{ secrets.CHARTING_ACCESS_TOKEN }}

    - name: Cache for Turbo
      uses: rharkor/caching-for-turbo@v1.5

    - name: Install pnpm
      uses: pnpm/action-setup@v4 

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.12
        cache: 'pnpm'
      
    - name: Install
      run: bash ./.scripts/vercel-install.sh ${{ secrets.ENV_NAME }}

    - name: Build all projects
      env: 
        PERPS_OCT_KEY: ${{ secrets.PERPS_OCT_KEY }}
        CHARTING_ACCESS_TOKEN: ${{ secrets.CHARTING_ACCESS_TOKEN }}
        NODE_OPTIONS: "--max_old_space_size=8192"
      run: pnpm run build:ipfs
     
     